version: '3.8'

services:

  duckling-server:
    image: rasa/duckling:latest
    ports:
      - "8000:8000"
    networks:
      - my_network

  rasa-server:
    image: rasa-bot:latest
    working_dir: /app
    build: ./path/to/docker/build/Dockerfile
    restart: always
    volumes:
      - ./actions:/app/actions
      - ./data:/app/data
    command: bash -c "rm -rf models/* && rasa train && rasa run --enable-api --cors \"*\" --debug"
    ports:
      - "5006:5005"
    networks:
      - my_network
    # Resource constraints
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '256m'

  rasa-actions-server:
    image: rasa-bot:latest
    working_dir: /app
    build: ./path/to/docker/build/Dockerfile
    restart: always
    volumes:
      - ./actions:/app/actions
      - ./utils:/app/utils
    command: ["rasa", "run", "actions"]
    ports:
    - '5055:5055'
    networks:
    - all

networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"